AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Stack - IAM Users, Roles, and Policies for Lake Formation

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev

Resources:
  # IAM Users
  LFDevUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub lf-lh-dev-user-o-sp5-${Environment}

  LFSuperUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub lf-lh-super-user-o-sp5-${Environment}

  # Access Keys
  LFDevUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref LFDevUser

  LFSuperUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref LFSuperUser

  # User Policies
  LFDevUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub lf-lh-dev-user-full-access-o-sp5-${Environment}
      Users:
        - !Ref LFDevUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
          - Effect: Allow
            Action: 'glue:*'
            Resource: '*'
          - Effect: Allow
            Action: 'athena:*'
            Resource: '*'
          - Effect: Allow
            Action: 'execute-api:Invoke'
            Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*'

  LFSuperUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub lf-lh-super-user-full-access-o-sp5-${Environment}
      Users:
        - !Ref LFSuperUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
          - Effect: Allow
            Action: 'glue:*'
            Resource: '*'
          - Effect: Allow
            Action: 'athena:*'
            Resource: '*'
          - Effect: Allow
            Action: 'execute-api:Invoke'
            Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*'

  # Glue Crawler Role
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub lf-lh-glue-crawler-role-o-sp5-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub GlueCrawlerCatalogOnlyAccess-o-sp5-${Environment}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::lf-lh-silver-bkt-o-sp5-${Environment}
                  - !Sub arn:aws:s3:::lf-lh-silver-bkt-o-sp5-${Environment}/*
              - Effect: Allow
                Action:
                  - glue:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - lakeformation:GetDataAccess
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws-glue/crawlers*

  # Glue Job Role
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub lf-lh-glue-job-role-o-sp5-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: !Sub GlueJobLakeFormationAccess-o-sp5-${Environment}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lakeformation:AddLFTagsToResource
                Resource: '*'
        - PolicyName: !Sub GlueJobLakeFormationTaggingAccess-o-sp5-${Environment}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lakeformation:AddLFTagsToResource
                  - lakeformation:RemoveLFTagsFromResource
                  - lakeformation:GetResourceLFTags
                  - lakeformation:ListLFTags
                  - lakeformation:GetLFTag
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetPartition
                  - glue:GetPartitions
                Resource: '*'

  # Dev User Role (assumable by Lambda)
  LFDevUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub lf-lh-dev-user-role-o-sp6-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringLike:
                aws:PrincipalArn:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/lf-athena-query-lambda-role-o-sp6-${Environment}
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/lf-athena-apikey-lambda-role-${Environment}
      Policies:
        - PolicyName: !Sub lf-lh-dev-user-athena-access-o-sp6-${Environment}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: '*'
              - Effect: Allow
                Action: 'glue:*'
                Resource: '*'
              - Effect: Allow
                Action: 'athena:*'
                Resource: '*'
              - Effect: Allow
                Action: 'lakeformation:GetDataAccess'
                Resource: '*'

  # Super User Role (assumable by Lambda)
  LFSuperUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub lf-lh-super-user-role-o-sp6-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringLike:
                aws:PrincipalArn:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/lf-athena-query-lambda-role-o-sp6-${Environment}
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/lf-athena-apikey-lambda-role-${Environment}
      Policies:
        - PolicyName: !Sub lf-lh-super-user-athena-access-o-sp6-${Environment}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: '*'
              - Effect: Allow
                Action: 'glue:*'
                Resource: '*'
              - Effect: Allow
                Action: 'athena:*'
                Resource: '*'
              - Effect: Allow
                Action: 'lakeformation:GetDataAccess'
                Resource: '*'

Outputs:
  LFDevUserArn:
    Description: ARN of the Dev User
    Value: !GetAtt LFDevUser.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LFDevUserArn

  LFSuperUserArn:
    Description: ARN of the Super User
    Value: !GetAtt LFSuperUser.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LFSuperUserArn

  LFDevUserRoleArn:
    Description: ARN of the Dev User Role (for Lambda to assume)
    Value: !GetAtt LFDevUserRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LFDevUserRoleArn

  LFSuperUserRoleArn:
    Description: ARN of the Super User Role (for Lambda to assume)
    Value: !GetAtt LFSuperUserRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LFSuperUserRoleArn

  GlueCrawlerRoleArn:
    Description: ARN of the Glue Crawler Role
    Value: !GetAtt GlueCrawlerRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GlueCrawlerRoleArn

  GlueJobRoleArn:
    Description: ARN of the Glue Job Role
    Value: !GetAtt GlueJobRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GlueJobRoleArn

  LFDevUserAccessKeyId:
    Description: Access Key ID for Dev User
    Value: !Ref LFDevUserAccessKey

  LFDevUserSecretAccessKey:
    Description: Secret Access Key for Dev User
    Value: !GetAtt LFDevUserAccessKey.SecretAccessKey

  LFSuperUserAccessKeyId:
    Description: Access Key ID for Super User
    Value: !Ref LFSuperUserAccessKey

  LFSuperUserSecretAccessKey:
    Description: Secret Access Key for Super User
    Value: !GetAtt LFSuperUserAccessKey.SecretAccessKey
