AWSTemplateFormatVersion: '2010-09-09'
Description: Master Stack - Orchestrates IAM, Glue, and Governance nested stacks

Parameters:
  TemplateS3Bucket:
    Type: String
    Description: S3 bucket containing nested stack templates
    Default: deploymen-bkt
  
  TemplateS3Prefix:
    Type: String
    Description: S3 prefix/folder for nested stack templates
    Default: lf-nested-stacks
  
  LambdaCodeS3Bucket:
    Type: String
    Description: S3 bucket containing Lambda deployment packages
    Default: deploymen-bkt
  
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  
  EnableOAuth:
    Type: String
    Description: Enable OAuth/Cognito authentication
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  EnableOAuthStack: !Equals [!Ref EnableOAuth, 'true']

Resources:
  # Stack 1: IAM Stack (creates users, roles, policies)
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Prefix}/iam-stack.yaml
      Parameters:
        Environment: !Ref Environment
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: IAM
        - Key: Project
          Value: LakeFormationAccessControl
        - Key: Environment
          Value: !Ref Environment

  # Stack 2: Glue Stack (creates database, bucket, crawler)
  # Depends on IAM stack for GlueCrawlerRole
  GlueStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Prefix}/glue-stack.yaml
      Parameters:
        Environment: !Ref Environment
        GlueCrawlerRoleArn: !GetAtt IAMStack.Outputs.GlueCrawlerRoleArn
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: Glue
        - Key: Project
          Value: LakeFormationAccessControl
        - Key: Environment
          Value: !Ref Environment

  # Stack 3: Governance Stack (creates LF tags and permissions)
  # Depends on both IAM and Glue stacks
  GovernanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
      - GlueStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Prefix}/governance-stack.yaml
      Parameters:
        Environment: !Ref Environment
        DatabaseName: !GetAtt GlueStack.Outputs.DatabaseName
        LFDevUserArn: !GetAtt IAMStack.Outputs.LFDevUserArn
        LFSuperUserArn: !GetAtt IAMStack.Outputs.LFSuperUserArn
        LFDevUserRoleArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserRoleArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
        GlueCrawlerRoleArn: !GetAtt IAMStack.Outputs.GlueCrawlerRoleArn
        GlueJobRoleArn: !GetAtt IAMStack.Outputs.GlueJobRoleArn
      TimeoutInMinutes: 15
      Tags:
        - Key: StackType
          Value: Governance
        - Key: Project
          Value: LakeFormationAccessControl
        - Key: Environment
          Value: !Ref Environment

  # Stack 4: Cognito Stack (optional - for OAuth authentication)
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Condition: EnableOAuthStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Prefix}/cognito-stack.yaml
      Parameters:
        Environment: !Ref Environment
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: Cognito
        - Key: Project
          Value: LakeFormationAccessControl
        - Key: Environment
          Value: !Ref Environment

  # Stack 5: Lambda Stack (creates Lambda function for Athena queries)
  # Depends on IAM and Glue stacks
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
      - GlueStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Prefix}/lambda-stack.yaml
      Parameters:
        Environment: !Ref Environment
        LFDevUserArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
        APIKeyMappingTableName: !Sub lf-api-key-mappings-o-sp6-${Environment}
        DatabaseName: !GetAtt GlueStack.Outputs.DatabaseName
        LambdaCodeS3Bucket: !Ref LambdaCodeS3Bucket
        LambdaCodeS3BucketRegion: !Ref AWS::Region
        LambdaCodeS3Key: lambda/athena-query-handler.zip
        CognitoUserPoolId: !If [EnableOAuthStack, !GetAtt CognitoStack.Outputs.UserPoolId, ""]
        CognitoAppClientId: !If [EnableOAuthStack, !GetAtt CognitoStack.Outputs.AppClientId, ""]
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: Lambda
        - Key: Project
          Value: LakeFormationAccessControl
        - Key: Environment
          Value: !Ref Environment

  # Stack 6: API Gateway Stack (creates REST API with API keys)
  # Depends on Lambda stack
  APIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Prefix}/api-stack.yaml
      Parameters:
        Environment: !Ref Environment
        LambdaFunctionArn: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
        OAuthLambdaFunctionArn: !If [EnableOAuthStack, !GetAtt LambdaStack.Outputs.OAuthLambdaFunctionArn, ""]
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: API
        - Key: Project
          Value: LakeFormationAccessControl
        - Key: Environment
          Value: !Ref Environment

  # Stack 7: DynamoDB Stack (creates API key mapping table)
  # Depends on API stack to get API key IDs and IAM stack for user ARNs
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - APIStack
      - IAMStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.amazonaws.com/${TemplateS3Prefix}/dynamodb-stack.yaml
      Parameters:
        Environment: !Ref Environment
        DevUserAPIKeyId: !GetAtt APIStack.Outputs.DevUserAPIKeyId
        SuperUserAPIKeyId: !GetAtt APIStack.Outputs.SuperUserAPIKeyId
        LFDevUserRoleArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserRoleArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: DynamoDB
        - Key: Project
          Value: LakeFormationAccessControl
        - Key: Environment
          Value: !Ref Environment

Outputs:
  # IAM Outputs
  LFDevUserArn:
    Description: ARN of the Dev User
    Value: !GetAtt IAMStack.Outputs.LFDevUserArn

  LFSuperUserArn:
    Description: ARN of the Super User
    Value: !GetAtt IAMStack.Outputs.LFSuperUserArn

  LFDevUserAccessKeyId:
    Description: Access Key ID for Dev User
    Value: !GetAtt IAMStack.Outputs.LFDevUserAccessKeyId

  LFDevUserSecretAccessKey:
    Description: Secret Access Key for Dev User (SENSITIVE)
    Value: !GetAtt IAMStack.Outputs.LFDevUserSecretAccessKey

  LFSuperUserAccessKeyId:
    Description: Access Key ID for Super User
    Value: !GetAtt IAMStack.Outputs.LFSuperUserAccessKeyId

  LFSuperUserSecretAccessKey:
    Description: Secret Access Key for Super User (SENSITIVE)
    Value: !GetAtt IAMStack.Outputs.LFSuperUserSecretAccessKey

  GlueCrawlerRoleArn:
    Description: ARN of the Glue Crawler Role
    Value: !GetAtt IAMStack.Outputs.GlueCrawlerRoleArn

  GlueJobRoleArn:
    Description: ARN of the Glue Job Role
    Value: !GetAtt IAMStack.Outputs.GlueJobRoleArn

  # Glue Outputs
  DatabaseName:
    Description: Name of the Glue Database
    Value: !GetAtt GlueStack.Outputs.DatabaseName

  BucketName:
    Description: Name of the S3 Bucket
    Value: !GetAtt GlueStack.Outputs.BucketName

  CrawlerName:
    Description: Name of the Glue Crawler
    Value: !GetAtt GlueStack.Outputs.CrawlerName

  # Governance Outputs
  DBAccessScopeTagKey:
    Description: DBAccessScope Tag Key
    Value: !GetAtt GovernanceStack.Outputs.DBAccessScopeTagKey

  PIITagKey:
    Description: PII Tag Key
    Value: !GetAtt GovernanceStack.Outputs.PIITagKey

  # API Outputs
  APIEndpoint:
    Description: API Gateway endpoint URL for Athena queries
    Value: !GetAtt APIStack.Outputs.APIEndpoint

  APIEndpointIAM:
    Description: API Gateway endpoint URL for IAM authenticated queries
    Value: !GetAtt APIStack.Outputs.APIEndpointIAM

  APIEndpointOAuth:
    Description: API Gateway endpoint URL for OAuth authenticated queries
    Value: !If [EnableOAuthStack, !GetAtt APIStack.Outputs.APIEndpointOAuth, "OAuth not enabled"]
    Condition: EnableOAuthStack

  DevUserAPIKey:
    Description: Dev User API Key Value (SENSITIVE - use to query with limited permissions)
    Value: !GetAtt DynamoDBStack.Outputs.DevUserAPIKeyValue

  SuperUserAPIKey:
    Description: Super User API Key Value (SENSITIVE - use to query with full permissions)
    Value: !GetAtt DynamoDBStack.Outputs.SuperUserAPIKeyValue

  # Cognito Outputs
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !If [EnableOAuthStack, !GetAtt CognitoStack.Outputs.UserPoolId, "OAuth not enabled"]
    Condition: EnableOAuthStack

  CognitoAppClientId:
    Description: Cognito App Client ID
    Value: !If [EnableOAuthStack, !GetAtt CognitoStack.Outputs.AppClientId, "OAuth not enabled"]
    Condition: EnableOAuthStack

  # Stack References
  IAMStackId:
    Description: IAM Stack ID
    Value: !Ref IAMStack

  GlueStackId:
    Description: Glue Stack ID
    Value: !Ref GlueStack

  GovernanceStackId:
    Description: Governance Stack ID
    Value: !Ref GovernanceStack

  LambdaStackId:
    Description: Lambda Stack ID
    Value: !Ref LambdaStack

  CognitoStackId:
    Description: Cognito Stack ID
    Value: !If [EnableOAuthStack, !Ref CognitoStack, "OAuth not enabled"]
    Condition: EnableOAuthStack

  APIStackId:
    Description: API Stack ID
    Value: !Ref APIStack

  DynamoDBStackId:
    Description: DynamoDB Stack ID
    Value: !Ref DynamoDBStack
