AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket Stack - For Lambda artifacts and deployment packages

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev

Resources:
  # S3 Bucket for Lambda deployment packages
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub lf-apikey-lambda-artifacts-${Environment}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Purpose
          Value: LambdaArtifacts

  # Bucket Policy to allow CloudFormation and Lambda service access
  LambdaArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaArtifactsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowLambdaServiceAccess
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub ${LambdaArtifactsBucket.Arn}/*
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
          
          - Sid: AllowCloudFormationAccess
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub ${LambdaArtifactsBucket.Arn}/*
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

Outputs:
  BucketName:
    Description: Name of the Lambda artifacts bucket
    Value: !Ref LambdaArtifactsBucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName

  BucketArn:
    Description: ARN of the Lambda artifacts bucket
    Value: !GetAtt LambdaArtifactsBucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-BucketArn
