AWSTemplateFormatVersion: '2010-09-09'
Description: Combined Lambda and API Stack with AWS API Gateway API Keys stored in Secrets Manager

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev
  
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the Lambda Execution Role from IAM stack
  
  LFDevUserArn:
    Type: String
    Description: ARN of the Dev User Role
  
  LFSuperUserArn:
    Type: String
    Description: ARN of the Super User Role
  
  LFAnalystUserArn:
    Type: String
    Description: ARN of the Analyst User Role
    Default: ""
  
  DatabaseName:
    Type: String
    Description: Name of the Glue database
  
  LambdaCodeS3Bucket:
    Type: String
    Description: S3 bucket containing Lambda deployment package
  
  LambdaCodeS3Key:
    Type: String
    Description: S3 key for Lambda deployment package
    Default: lambda/api-key-poc/athena-query-apikey-dev.zip
  
  AthenaBucketName:
    Type: String
    Description: S3 bucket name for Athena query results
  
  AthenaOutputPrefix:
    Type: String
    Description: S3 prefix for Athena query results

Resources:
  # ==========================================
  # DynamoDB Table - Maps Secret Name to Role ARN
  # ==========================================
  APIKeyMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub lf-apikey-mappings-v3-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: secretName
          AttributeType: S
        - AttributeName: groupLabel
          AttributeType: S
      KeySchema:
        - AttributeName: secretName
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GroupLabelIndex
          KeySchema:
            - AttributeName: groupLabel
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: LakeFormationAccessControl

  # ==========================================
  # API Gateway REST API
  # ==========================================
  AthenaQueryAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub lf-athena-apikey-api-apk-${Environment}
      Description: !Sub API Gateway for Athena queries with Lake Formation TBAC - ${Environment}
      EndpointConfiguration:
        Types:
          - REGIONAL
      ApiKeySourceType: HEADER
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: LakeFormationAccessControl

  QueryResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref AthenaQueryAPI
      ParentId: !GetAtt AthenaQueryAPI.RootResourceId
      PathPart: query

  # ==========================================
  # API Gateway API Keys (created first, then stored in Secrets Manager)
  # ==========================================
  DevUserAPIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub lf-apikey-dev-user-v3-${Environment}
      Description: !Sub API Key for Dev User - ${Environment}
      Enabled: true

  SuperUserAPIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub lf-apikey-super-user-v3-${Environment}
      Description: !Sub API Key for Super User - ${Environment}
      Enabled: true

  AnalystUserAPIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub lf-apikey-analyst-user-v3-${Environment}
      Description: !Sub API Key for Analyst User - ${Environment}
      Enabled: true

  # ==========================================
  # Lambda Function
  # ==========================================
  AthenaQueryFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref APIKeyMappingTable
          ENVIRONMENT: !Ref Environment
          DATABASE_NAME: !Ref DatabaseName
          ATHENA_OUTPUT_BUCKET: !Ref AthenaBucketName
          ATHENA_OUTPUT_PREFIX: !Ref AthenaOutputPrefix
          SECRET_KEY_PREFIX: lf-apikey-
      Timeout: 300
      MemorySize: 512
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # API Gateway Method - API Key Required: true (Gateway validates presence, Lambda validates value)
  # ==========================================
  QueryMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AthenaQueryAPI
      ResourceId: !Ref QueryResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true  # Gateway ensures x-api-key header exists, Lambda validates the actual value
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AthenaQueryFunction.Arn}/invocations

  QueryOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AthenaQueryAPI
      ResourceId: !Ref QueryResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiGatewayInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AthenaQueryFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AthenaQueryAPI}/*/*

  # ==========================================
  # API Gateway Deployment
  # ==========================================
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - QueryMethod
      - QueryOptionsMethod
    Properties:
      RestApiId: !Ref AthenaQueryAPI

  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref AthenaQueryAPI
      DeploymentId: !Ref APIDeployment
      StageName: !Ref Environment

  # ==========================================
  # Custom Resource to Store API Keys in Secrets Manager and Create DynamoDB Mappings
  # ==========================================
  StoreAPIKeysFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt StoreAPIKeysFunctionRole.Arn
      Timeout: 300
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse
          
          apigateway = boto3.client('apigateway')
          secretsmanager = boto3.client('secretsmanager')
          dynamodb = boto3.client('dynamodb')
          
          def handler(event, context):
              try:
                  request_type = event['RequestType']
                  
                  if request_type == 'Delete':
                      # Cleanup secrets on stack deletion
                      try:
                          mappings = event['ResourceProperties']['APIKeyMappings']
                          for mapping in mappings:
                              secret_name = mapping['SecretName']
                              try:
                                  secretsmanager.delete_secret(
                                      SecretId=secret_name,
                                      ForceDeleteWithoutRecovery=True
                                  )
                                  print(f"Deleted secret: {secret_name}")
                              except secretsmanager.exceptions.ResourceNotFoundException:
                                  print(f"Secret {secret_name} already deleted")
                      except Exception as e:
                          print(f"Cleanup warning: {str(e)}")
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return
                  
                  # Process all API key mappings
                  mappings = event['ResourceProperties']['APIKeyMappings']
                  table_name = event['ResourceProperties']['TableName']
                  env = event['ResourceProperties']['Environment']
                  response_data = {}
                  
                  print(f"Processing {len(mappings)} API key mappings")
                  
                  for mapping in mappings:
                      api_key_id = mapping['APIKeyId']
                      user_name = mapping['UserName']
                      group_label = mapping['GroupLabel']
                      role_arn = mapping['RoleArn']
                      secret_name = mapping['SecretName']
                      
                      # Get API key value from API Gateway
                      print(f"Retrieving API key for {user_name}...")
                      key_response = apigateway.get_api_key(apiKey=api_key_id, includeValue=True)
                      api_key_value = key_response['value']
                      
                      # Store in Secrets Manager
                      try:
                          secret_response = secretsmanager.create_secret(
                              Name=secret_name,
                              Description=f'{user_name} API Key - {group_label} group',
                              SecretString=json.dumps({
                                  'apiKey': api_key_value,
                                  'userName': user_name,
                                  'groupLabel': group_label,
                                  'apiKeyId': api_key_id
                              }),
                              Tags=[
                                  {'Key': 'LFAPIKeyType', 'Value': 'api-key'},
                                  {'Key': 'GroupLabel', 'Value': group_label},
                                  {'Key': 'Environment', 'Value': env},
                                  {'Key': 'ManagedBy', 'Value': 'CloudFormation'},
                                  {'Key': 'Project', 'Value': 'LakeFormationAccessControl'}
                              ]
                          )
                          secret_arn = secret_response['ARN']
                          print(f"Created secret: {secret_name}")
                      except secretsmanager.exceptions.ResourceExistsException:
                          # Update existing secret (handles stack updates)
                          print(f"Secret {secret_name} exists, updating...")
                          secretsmanager.put_secret_value(
                              SecretId=secret_name,
                              SecretString=json.dumps({
                                  'apiKey': api_key_value,
                                  'userName': user_name,
                                  'groupLabel': group_label,
                                  'apiKeyId': api_key_id
                              })
                          )
                          secret_arn = secretsmanager.describe_secret(SecretId=secret_name)['ARN']
                          print(f"Updated secret: {secret_name}")
                      
                      # Store mapping in DynamoDB: secretName -> roleArn
                      dynamodb.put_item(
                          TableName=table_name,
                          Item={
                              'secretName': {'S': secret_name},
                              'secretArn': {'S': secret_arn},
                              'roleArn': {'S': role_arn},
                              'userName': {'S': user_name},
                              'groupLabel': {'S': group_label},
                              'apiKeyId': {'S': api_key_id}
                          }
                      )
                      print(f"Created DynamoDB mapping: {secret_name} -> {group_label} -> {role_arn}")
                      
                      # Add to response data
                      response_data[f'{user_name}SecretArn'] = secret_arn
                      response_data[f'{user_name}SecretName'] = secret_name
                      response_data[f'{user_name}GroupLabel'] = group_label
                  
                  response_data['ProcessedCount'] = len(mappings)
                  print(f"Successfully processed {len(mappings)} API keys")
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
                  
              except Exception as e:
                  print(f"Error: {str(e)}")
                  import traceback
                  traceback.print_exc()
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  StoreAPIKeysFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ManageSecretsAndDynamoDB
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:GET
                Resource: '*'
              - Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                  - secretsmanager:PutSecretValue
                  - secretsmanager:TagResource
                  - secretsmanager:DescribeSecret
                  - secretsmanager:DeleteSecret
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt APIKeyMappingTable.Arn

  # ==========================================
  # Usage Plan (not required but good practice)
  # ==========================================
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: APIStage
    Properties:
      ApiStages:
        - ApiId: !Ref AthenaQueryAPI
          Stage: !Ref Environment

  UsagePlanKeyDev:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref DevUserAPIKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  UsagePlanKeySuper:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref SuperUserAPIKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  UsagePlanKeyAnalyst:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref AnalystUserAPIKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  # ==========================================
  # Custom Resource Invocation
  # SINGLE SOURCE OF TRUTH: All mapping logic here
  # ==========================================
  StoreAPIKeysInSecrets:
    Type: Custom::StoreAPIKeys
    DependsOn:
      - DevUserAPIKey
      - SuperUserAPIKey
      - AnalystUserAPIKey
      - APIKeyMappingTable
    Properties:
      ServiceToken: !GetAtt StoreAPIKeysFunction.Arn
      TableName: !Ref APIKeyMappingTable
      Environment: !Ref Environment
      Version: "2.7"  # Force custom resource update
      # Declarative array: APIKeyId + UserName + GroupLabel + RoleArn + SecretName
      APIKeyMappings:
        - APIKeyId: !Ref DevUserAPIKey
          UserName: dev-user
          GroupLabel: developer
          RoleArn: !Ref LFDevUserArn
          SecretName: !Sub lf-apikey-dev-user-v3-${Environment}
        
        - APIKeyId: !Ref SuperUserAPIKey
          UserName: super-user
          GroupLabel: admin
          RoleArn: !Ref LFSuperUserArn
          SecretName: !Sub lf-apikey-super-user-v3-${Environment}
        
        - APIKeyId: !Ref AnalystUserAPIKey
          UserName: analyst-user
          GroupLabel: analyst
          RoleArn: !Ref LFSuperUserArn
          SecretName: !Sub lf-apikey-analyst-user-v3-${Environment}

Outputs:
  APIEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${AthenaQueryAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/query
    Export:
      Name: !Sub ${AWS::StackName}-APIEndpoint
  
  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt AthenaQueryFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaFunctionArn
  
  DevUserAPIKeyValue:
    Description: Dev User API Key (retrieve from API Gateway console)
    Value: !Ref DevUserAPIKey
    Export:
      Name: !Sub ${AWS::StackName}-DevUserAPIKeyId
  
  SuperUserAPIKeyValue:
    Description: Super User API Key (retrieve from API Gateway console)
    Value: !Ref SuperUserAPIKey
    Export:
      Name: !Sub ${AWS::StackName}-SuperUserAPIKeyId
  
  AnalystUserAPIKeyValue:
    Description: Analyst User API Key (retrieve from API Gateway console)
    Value: !Ref AnalystUserAPIKey
    Export:
      Name: !Sub ${AWS::StackName}-AnalystUserAPIKeyId
  
  DynamoDBTableName:
    Description: DynamoDB table name for secret to role mappings
    Value: !Ref APIKeyMappingTable
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDBTableName
  
  APIKeyMappingInfo:
    Description: Summary of API key mappings created
    Value: !Sub |
      dev-user (${DevUserAPIKey}): developer group -> ${LFDevUserArn}
      super-user (${SuperUserAPIKey}): admin group -> ${LFSuperUserArn}
  
  LambdaExecutionRoleArn:
    Description: Lambda execution role ARN that needs to assume LF roles
    Value: !Ref LambdaExecutionRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaExecutionRoleArn

