AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack - API Key Based Lake Formation Access Control POC

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  
  DatabaseName:
    Type: String
    Description: Name of the existing Glue database
    Default: lf-lh-silver-db-o-sp5-dev
  
  LambdaArtifactsBucket:
    Type: String
    Description: S3 bucket name for Lambda artifacts (created from bucket stack)
    Default: lf-apikey-lambda-artifacts-dev-480399101976
  
  LambdaCodeS3Key:
    Type: String
    Description: S3 key for Lambda deployment package
    Default: lambda/api-key-poc/athena-query-apikey-dev.zip
  
  AthenaBucketName:
    Type: String
    Description: S3 bucket name for Athena query results
    Default: aws-athena-query-results-480399101976-ap-southeast-2
  
  AthenaOutputPrefix:
    Type: String
    Description: S3 prefix for Athena query results
    Default: api-key-poc/

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
          - DatabaseName
      - Label:
          default: Lambda Configuration
        Parameters:
          - LambdaArtifactsBucket
          - LambdaCodeS3Key

Resources:
  # Stack 1: IAM Stack - Creates IAM roles for dev and super users
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/lf-lh-nest-sts/lf-api-key/iam-apikey-stack.yaml
      Parameters:
        Environment: !Ref Environment
        AthenaBucketName: !Ref AthenaBucketName
        AthenaOutputPrefix: !Ref AthenaOutputPrefix
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: IAM
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Environment
          Value: !Ref Environment

  # Stack 2: Lambda Stack - Creates Secrets Manager, DynamoDB table and Lambda function
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/lf-lh-nest-sts/lf-api-key/lambda-apikey-stack.yaml
      Parameters:
        Environment: !Ref Environment
        LFDevUserArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
        DatabaseName: !Ref DatabaseName
        LambdaCodeS3Bucket: !Ref LambdaArtifactsBucket
        LambdaCodeS3Key: !Ref LambdaCodeS3Key
        AthenaBucketName: !Ref AthenaBucketName
        AthenaOutputPrefix: !Ref AthenaOutputPrefix
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: Lambda
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Environment
          Value: !Ref Environment

  # Stack 3: API Gateway Stack
  APIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaStack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/lf-lh-nest-sts/lf-api-key/api-apikey-stack.yaml
      Parameters:
        Environment: !Ref Environment
        LambdaFunctionArn: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
        LFDevUserRoleArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserRoleArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
        APIKeyMappingTableName: !GetAtt LambdaStack.Outputs.APIKeyMappingTableName
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: APIGateway
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Environment
          Value: !Ref Environment

  # Stack 4: Lake Formation Governance Stack
  GovernanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/lf-lh-nest-sts/lf-api-key/governance-apikey-stack.yaml
      Parameters:
        Environment: !Ref Environment
        DatabaseName: !Ref DatabaseName
        LFDevUserRoleArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserRoleArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: LakeFormationGovernance
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Environment
          Value: !Ref Environment

Outputs:
  # IAM Outputs
  DevUserRoleArn:
    Description: ARN of the Dev User Role
    Value: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-DevUserRoleArn

  SuperUserRoleArn:
    Description: ARN of the Super User Role
    Value: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-SuperUserRoleArn

  # Lambda Outputs
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionName

  DynamoDBTableName:
    Description: Name of the DynamoDB table for API key mappings
    Value: !GetAtt LambdaStack.Outputs.APIKeyMappingTableName
  
  DevUserSecretArn:
    Description: ARN of the Secrets Manager secret containing Dev User API key
    Value: !GetAtt LambdaStack.Outputs.DevUserAPIKeySecretArn
  
  SuperUserSecretArn:
    Description: ARN of the Secrets Manager secret containing Super User API key
    Value: !GetAtt LambdaStack.Outputs.SuperUserAPIKeySecretArn

  # API Gateway Outputs
  APIEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt APIStack.Outputs.QueryEndpoint

  # DevUserAPIKeyId:
  #   Description: API Key ID for Dev User
  #   Value: !GetAtt APIStack.Outputs.DevUserApiKeyId

  # SuperUserAPIKeyId:
  #   Description: API Key ID for Super User
  #   Value: !GetAtt APIStack.Outputs.SuperUserApiKeyId

  # Test Command - For manual Lambda invocation
  TestCommandManual:
    Description: Test the Lambda function manually
    Value: !Sub |
      # Get the API keys from Secrets Manager:
      DEV_KEY=$(aws secretsmanager get-secret-value --secret-id ${LambdaStack.Outputs.DevUserAPIKeySecretArn} --query SecretString --output text | jq -r .apiKey)
      SUPER_KEY=$(aws secretsmanager get-secret-value --secret-id ${LambdaStack.Outputs.SuperUserAPIKeySecretArn} --query SecretString --output text | jq -r .apiKey)
      
      # Test Lambda directly:
      aws lambda invoke \
        --function-name ${LambdaStack.Outputs.LambdaFunctionName} \
        --payload '{"headers":{"x-api-key":"'$DEV_KEY'"},"body":"{\"tableName\":\"members\",\"limit\":5}"}' \
        --region ${AWS::Region} \
        response.json
      
      cat response.json
