AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack - API Key Based Lake Formation Access Control POC

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  
  DatabaseName:
    Type: String
    Description: Name of the existing Glue database
    Default: lf-lh-silver-db-o-sp5-dev
  
  LambdaArtifactsBucket:
    Type: String
    Description: S3 bucket name for Lambda artifacts (created from bucket stack)
    Default: lf-apikey-lambda-artifacts-dev-480399101976
  
  LambdaCodeS3Key:
    Type: String
    Description: S3 key for Lambda deployment package
    Default: lambda/api-key-poc/athena-query-apikey-dev.zip
  
  AthenaBucketName:
    Type: String
    Description: S3 bucket name for Athena query results
    Default: aws-athena-query-results-480399101976-ap-southeast-2
  
  AthenaOutputPrefix:
    Type: String
    Description: S3 prefix for Athena query results
    Default: api-key-poc/

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
          - DatabaseName
      - Label:
          default: Lambda Configuration
        Parameters:
          - LambdaArtifactsBucket
          - LambdaCodeS3Key

Resources:
  # Stack 1: IAM Stack - Creates IAM roles for dev and super users
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/lf-lh-nest-sts/lf-api-key/iam-apikey-stack.yaml
      Parameters:
        Environment: !Ref Environment
        AthenaBucketName: !Ref AthenaBucketName
        AthenaOutputPrefix: !Ref AthenaOutputPrefix
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: IAM
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Environment
          Value: !Ref Environment

  # Stack 2: Combined Lambda + API Stack - Creates API Gateway, Lambda, DynamoDB, Secrets Manager, API Keys
  LambdaAPIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/lf-lh-nest-sts/lf-api-key/lambda-api-stack.yaml?v=5.0
      Parameters:
        Environment: !Ref Environment
        LambdaExecutionRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        LFDevUserArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
        DatabaseName: !Ref DatabaseName
        LambdaCodeS3Bucket: !Ref LambdaArtifactsBucket
        LambdaCodeS3Key: !Ref LambdaCodeS3Key
        AthenaBucketName: !Ref AthenaBucketName
        AthenaOutputPrefix: !Ref AthenaOutputPrefix
      TimeoutInMinutes: 15
      Tags:
        - Key: StackType
          Value: LambdaAPI
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Environment
          Value: !Ref Environment

  # Stack 3: Lake Formation Governance Stack
  GovernanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMStack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/lf-lh-nest-sts/lf-api-key/governance-apikey-stack.yaml
      Parameters:
        Environment: !Ref Environment
        DatabaseName: !Ref DatabaseName
        LFDevUserRoleArn: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
        LFSuperUserRoleArn: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
      TimeoutInMinutes: 10
      Tags:
        - Key: StackType
          Value: LakeFormationGovernance
        - Key: Project
          Value: LakeFormationAPIKeyPOC
        - Key: Environment
          Value: !Ref Environment

Outputs:
  # IAM Outputs
  DevUserRoleArn:
    Description: ARN of the Dev User Role
    Value: !GetAtt IAMStack.Outputs.LFDevUserRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-DevUserRoleArn

  SuperUserRoleArn:
    Description: ARN of the Super User Role
    Value: !GetAtt IAMStack.Outputs.LFSuperUserRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-SuperUserRoleArn

  # Lambda Outputs
  # Lambda and API Outputs
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaAPIStack.Outputs.LambdaFunctionArn

  DynamoDBTableName:
    Description: Name of the DynamoDB table for API key mappings
    Value: !GetAtt LambdaAPIStack.Outputs.DynamoDBTableName

  APIEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt LambdaAPIStack.Outputs.APIEndpoint

  DevUserAPIKeyId:
    Description: API Key ID for Dev User
    Value: !GetAtt LambdaAPIStack.Outputs.DevUserAPIKeyValue

  SuperUserAPIKeyId:
    Description: API Key ID for Super User
    Value: !GetAtt LambdaAPIStack.Outputs.SuperUserAPIKeyValue

  # Test Command
  TestCommandManual:
    Description: Test the API with API keys
    Value: !Sub |
      # Get API key values:
      DEV_KEY=$(aws apigateway get-api-key --api-key ${LambdaAPIStack.Outputs.DevUserAPIKeyValue} --include-value --region ${AWS::Region} --query value --output text)
      SUPER_KEY=$(aws apigateway get-api-key --api-key ${LambdaAPIStack.Outputs.SuperUserAPIKeyValue} --include-value --region ${AWS::Region} --query value --output text)
      
      # Test with Dev key:
      curl -X POST ${LambdaAPIStack.Outputs.APIEndpoint} \
        -H "x-api-key: $DEV_KEY" \
        -H "Content-Type: application/json" \
        -d '{"tableName":"members","limit":5}'

